### ISSUE TITLE
current working directory

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/TriFusion#138]
When the app is opened in a given working directory, the file chooser could open in this working directory instead of the default home directory.

**Comment by ODiogoSilva** [comment]
This will be on hold. The issue here is that when the app is launched from the desktop environment instead from a terminal, the current working directory may not be ideal.

**Comment by StuntsPT** [comment]
Especially if you port it to windows where it gets installed into "god knows where" directory hierarchy.
For me it's a +1 for starting in the home dir.
If you **really** want to improve in this matter, make sure the program remembers the location of your last opened file, and the next "open" dialogue starts there.

**Comment by ODiogoSilva** [comment]
@StuntsPT That is already implemented in the current build.

**Comment by StuntsPT** [comment]
I'm out of date then, I don't remember it doing that last time I tried it. Carry on then. xD

**Comment by Camandros** [comment]
This needs testing, but perhaps the best solution is to set the initial working directory based on the OS and execution place. It would be something like:

**if** windows:
    dir = home
**elif** linux:
    current:_dir = `pwd`
    **if** current_dir.startswith("/usr"):
        dir = home
    **else**
        dir = current_dir

The last location used is kept the same. This would be only for starters.

**Comment by ODiogoSilva** [comment]
If the installation is local on a *unix machine, current_dir would be somewhere in /home, and the initial working directory would still be the app's path. In this case, I'm not sure how to check for this. Seems simpler to set the home folder as default and perhaps create an option in the app's preferences to change the default initial working directory.
