### ISSUE TITLE
Launch app with input files from terminal

### ISSUE THREAD

**Issue by ODiogoSilva** [ODiogoSilva/TriFusion#163]
This will probably be useful only for *unix users only, but the app could be launched from the terminal with the input files already provided through some arguments. (e.g. TriFusion.py -aln *.fas).

Since there are two main input file types (alignments and proteomes) two options should be available to distinguish them.

**Comment by Camandros** [comment]
Or with a folder to be used as initial working directory

**Comment by ODiogoSilva** [comment]
Yes! The app already handles cases where the input is a directory (https://github.com/ODiogoSilva/TriFusion/blob/master/TriFusion.py#L7915), so there's no need to further parse the arguments in that regard.

**Comment by tiagofilipe12** [comment]
Can't replicate this issue. The app seems to normally load the files and store them elsewhere. Thus, removing the original input files doesn't crash the app, per se.
