### ISSUE TITLE
Zorro option allways retrieving an error message

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/TriFusion#191]
Whenever I try to use the zorro option in concatenation (process), TriFusion gives an error message that the first file that I am trying to concatenate using zorro option does not exist. I tryed using files with spaces and with no spaces nor special characteres but the problem seems to remain.

**Comment by ODiogoSilva** [comment]
When a suffix is specified on the Zorro dialog, the app automatically searches for a file with the zorro weights whose name is the same as the input file(s), plus the provided suffix (See help "?" for Zorro). If more than one file is not found, it issues the error.
