### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/TriFusion#192]
I have a suggestion/question. I know when you have several files it may be hard to allways check each file for duplicated entries and to tell the user if he wants to overwrite them or not. However, I noticed that when you create a fasta file previously with the output you want and after you generate new fasta and other nexus and phylip, the result is somehow confusing:

- The new fasta cames with a new _conv label (since there is already a file with the same name in that directory), e.g, "something"_conv.
- However, the other files phylip and nexus will not come with the _conv label, which may be confusing, particularly when you have several files in the same directory.

**Comment by ODiogoSilva** [comment]
In the current build, file names only receive the "_conv" suffix if a file with an identical name is already present in the output directory. However, this is checked for each output file, which means that some may receive the suffix while others don't.

**Comment by tiagofilipe12** [comment]
I suggest that, when one of the outputs has the same name of an existing file, all the output options selected for that run have the same suffix.
