### ISSUE TITLE
Orthology search execution popup

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/TriFusion#251]
While executing processes related with orthology search TriFusion have a progress bar stating which processes are currently being performed. However, it would be nice to have something like you print to terminal, i.e., retrieving the percentage of that process that has already been performed (like this "44:18 429Mb   100.0% Searching goodProteins_db, 100.0% matched"). I think this would give the user a better idea of the time things will take to finish.

**Comment by ODiogoSilva** [comment]
The orthology search execution dialog was improved to give a better perception of progress. However, getting the progress of third party applications, such as Usearch and mcl is much more challenging (due to unbuffered outputs). For now, progression cannot be provided for theses tasks.

**Comment by tiagofilipe12** [comment]
For now, I think the progress is very detailed and gives the notion of progress that the user looks for. Too bad the app cannot track the progress of USEARCH and orthoMCL.
