### ISSUE TITLE
searching for files in open files menu

### ISSUE THREAD

**Issue by tiagofilipe12** [ODiogoSilva/TriFusion#28]
When browsing in the open files menu it might be handy to have some type of search like in a File Manager, such as ctrl + f or even by typing the first letter of the desired file. It would be nice if you implement this.

**Comment by ODiogoSilva** [comment]
A "Find" field has been added to the file chooser, which ca be used to search for files or directories using text input. In the current version the "Find" text input field is automatically focused when the file chooser screen opens, and the search is executed on every change to the text input.

Re-open if there are further suggestions/bugs.

**Comment by ODiogoSilva** [comment]
Last commit adds the keybinding "ctrl+f" to focus on the text input of the "Find" field
