### ISSUE TITLE
error in command line run

### ISSUE THREAD

**Issue by dvorikus** [ODiogoSilva/TriFusion#281]
Hi,
I got this following error while runing the pipeline. I figure that it has something to do with fact that USEARCH does not produce any files - both AllVsAll.out and goodProteins are empty. So the subsequent parsing is impossible. Can you please give me a hand with it?

dvorikus@dvorikus:~/HGT$ orthomcl_pipeline -n -in ./trifusion/small --min-species 5 --max-gene-copy 1 -o ./trifusion/small.res/ -np 16
[OrthoMCl Pipeline] Executing OrthoMCL pipeline at 01/02/2018 04:27:11
[OrthoMCl Pipeline] Creating sqlite database
[OrthoMCl Pipeline] Adjusting proteome files
[OrthoMCl Pipeline] 	 Using unique header field 0
[OrthoMCl Pipeline] 	 Using unique header field 0
[OrthoMCl Pipeline] 	 Using unique header field 0
[OrthoMCl Pipeline] 	 Using unique header field 1
[OrthoMCl Pipeline] 	 Using unique header field 0
[OrthoMCl Pipeline] Filtering proteome files
[OrthoMCl Pipeline] Perfoming USEARCH All-vs-All (may take a while...)
usearch v10.0.240_i86linux32, 4.0Gb RAM (132Gb total), 24 cores
(C) Copyright 2013-17 Robert C. Edgar, all rights reserved.
http://drive5.com/usearch

License: p.dvorak@upol.cz

usearch -ublast /home/dvorikus/HGT/./trifusion/small.res/backstage_files/goodProteins -db /home/dvorikus/HGT/./trifusion/small.res/backstage_files/goodProteins -blast6out ./trifusion/small.res/backstage_files/AllVsAll.out -evalue 1e-05 --maxaccepts 0 -threads 16

---Fatal error---
Empty file /home/dvorikus/HGT/./trifusion/small.res/backstage_files/goodProteins
[OrthoMCl Pipeline] Parsing BLAST output
hspspans
Traceback (most recent call last):
  File "/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/orthomcl_pipeline.py", line 594, in main
    blast_parser(usearch_out_name, output_dir, tmp_dir, None)
  File "/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/orthomcl_pipeline.py", line 281, in blast_parser
    nm)
  File "/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/ortho/orthomclBlastParser.py", line 253, in orthomcl_blast_parser
    print_previous_subject(subject, cur)
  File "/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/ortho/orthomclBlastParser.py", line 98, in print_previous_subject
    non_overlap = non_overlapping_match(subject)
  File "/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/ortho/orthomclBlastParser.py", line 134, in non_overlapping_match
    hsps = subject["hspspans"]
KeyError: 'hspspans'
[OrthoMCl Pipeline-Error] Program exited with errors!

**Comment by ODiogoSilva** [comment]
Hi,

Can you tell me a bit more about the input data set, like the number of genomes and size of the goodProteins file?

**Comment by dvorikus** [comment]
Thank you for the answer. I tried two datasets. 5 and 78 proteoms. Size of
each proteom was between 1000 to 6000 genes. GoodProtein was empty. Let me
know if you need anything else.

On Feb 1, 2018 7:10 PM, "Diogo Silva" <notifications@github.com> wrote:

Hi,

Can you tell me a bit more about the input data set, like the number of
genomes and size of the goodProteins file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ODiogoSilva/TriFusion/issues/281#issuecomment-362353029>,
or mute the thread

**Comment by ODiogoSilva** [comment]
Ok, so if the GoodProtein file is empty, the issue is before usearch. The fasta headers of the proteomes also seem to be OK since unique fields are found in all of the 5 proteomes. 

Can you share a few examples of those proteomes? Also, there should also be a "poorProteins.txt" file created that stores all proteins that did not pass the sequence quality step. Does this file contain protein sequences?

**Comment by dvorikus** [comment]
The files did not get through, I'm trying compressed files.

My previous message:
"poorProteins.txt" is also empty. I attached few proteomes. Thank you for
help.

2018-02-02 0:56 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by ODiogoSilva** [comment]
Any success? I suggest transfer.sh to send the files?

**Comment by dvorikus** [comment]
The proteoms are attached. It is much smaller when compressed. I think it
should go through.

Petr

2018-02-03 22:44 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by ODiogoSilva** [comment]
Sorry, but I'm not receiving the attachments here on github issue tracker.

**Comment by dvorikus** [comment]
I see. Sorry! The dropbox should work.

https://www.dropbox.com/s/vggb93edkz1sk1n/sample.proteoms.tar.gz?dl=0

2018-02-05 14:26 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by ODiogoSilva** [comment]
Ok, so I executed orthomcl_pipeline with the genomes you have provide and the run reaches the end successfully. Can you provide me the version of trifusion that you are using? You can check this by typing in the terminal:

`python2 -c "import trifusion; print trifusion.__version__"`

Have you tried to run with these 4 proteomes? I see from your first log that there is a proteome whose unique ID field is 1, instead of 0. That shouldn't be a problem, but it would allow me to fully reproduce your command.

**Comment by ODiogoSilva** [comment]
Ok, nevermind, I think I've found the issue. Try calling orthomcl_pipeline with a slight modification in your command (basically remove the "./" from the beginning of the input and output paths:

`orthomcl_pipeline -n -in trifusion/small --min-species 5 --max-gene-copy 1 -o trifusion/small.res/ -np 16`

Assuming that you are in the correct directory

**Comment by dvorikus** [comment]
Thank you. I will try it when I have computation capacity on our
workstation. I let you know.

Petr

2018-02-05 14:55 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by dvorikus** [comment]
Thank you. It worked. What a stupid mistake I made.


2018-02-05 14:55 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by ODiogoSilva** [comment]
No problem at all. This is actually a common behavior when declaring paths on unix. I'll leave this issue open until I provide a more robust handling of these paths. Thank you for your input.

**Comment by dvorikus** [comment]
Hi Diogo,
I worked on my dataset a little bit more and it works with 5 proteoms, but
I tried later 78 and it produced following error. It may be again some
syntax problem, but I was unable to solve it. Can you please help me again?

orthomcl_pipeline -n -in pro_hal --max-gene-copy 1 -o nostocales -np  8
[OrthoMCl Pipeline] Executing OrthoMCL pipeline at 08/02/2018 01:16:16
[OrthoMCl Pipeline] Creating sqlite database
[OrthoMCl Pipeline] Adjusting proteome files
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 1
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Using unique header field 0
[OrthoMCl Pipeline] Filtering proteome files
[OrthoMCl Pipeline] Perfoming USEARCH All-vs-All (may take a while...)
usearch v10.0.240_i86linux32, 4.0Gb RAM (132Gb total), 24 cores
(C) Copyright 2013-17 Robert C. Edgar, all rights reserved.
http://drive5.com/usearch

License: p.dvorak@upol.cz

00:03 226Mb   100.0% Reading
/home/dvorikus/HGT/trifusion/nostocales/backstage_files/goodProteins
00:06 192Mb   100.0% Masking (fastnucleo)

00:13 205Mb   100.0% Word stats
00:13 741Mb   100.0% Alloc rows
00:34 797Mb   100.0% Build index
02:07:47 1.9Gb   100.0% Searching goodProteins, 100.0% matched
[OrthoMCl Pipeline] Parsing BLAST output
invalid literal for int() with base 10: '40.9'
Traceback (most recent call last):
  File
"/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/orthomcl_pipeline.py",
line 594, in main
    blast_parser(usearch_out_name, output_dir, tmp_dir, None)
  File
"/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/orthomcl_pipeline.py",
line 281, in blast_parser
    nm)
  File
"/home/dvorikus/.local/lib/python2.7/site-packages/trifusion/ortho/orthomclBlastParser.py",
line 215, in orthomcl_blast_parser
    length = int(splitted[3])
ValueError: invalid literal for int() with base 10: '40.9'
[OrthoMCl Pipeline-Error] Program exited with errors!





2018-02-06 15:35 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by fernandoblalves** [comment]
Hi,

We've looked into the code and found no reasonable reason for this error. Can you kindly provide us with the 78 proteome dataset so we can perform further tests and discover the bug?

Thanks

**Comment by dvorikus** [comment]
No problem. I uploaded the proteoms to Dropbox:
https://www.dropbox.com/s/9byuan6llpzuupa/cyano.proteoms.tar.gz?dl=0

Thank you for your time,

Petr

2018-02-08 16:57 GMT+01:00 Fernando Alves <notifications@github.com>:

**Comment by ODiogoSilva** [comment]
Thank you Petr. We'll look into this and include the fix in the next release, which was slated for this weekend.

**Comment by dvorikus** [comment]
Great to hear that. Thank you!

2018-02-09 10:25 GMT+01:00 Diogo Silva <notifications@github.com>:

**Comment by ODiogoSilva** [comment]
We found the source of the issue and are currently performing more testing before the release. The problem was the presence of a space in one of the proteome input files, namely:

`Nostocs_sp_Peltigera_membranacea_cyanobiont 213_GCA_002245975.1_ASM224597v1_protein.fasta`

which, without proper sanitation, would break the usearch output parser. While the release is pending, you can bypass this issue by removing the whitespace from this file. I also note that the name of the input proteomes will determine the "species name" in the final ortholog files. You might find it useful to rename the proteome files early on (in this case, `Nostocs_sp_Peltigera_membranacea_cyanobiont_213.fasta`), though this is completely optional.

**Comment by dvorikus** [comment]
Thank you so much! I will test it.


2018-02-10 12:59 GMT+01:00 Diogo Silva <notifications@github.com>:
