### ISSUE TITLE
missing -fi in TriSeq [command line version]

### ISSUE THREAD

**Issue by MafaldaSFerreira** [ODiogoSilva/TriFusion#284]
While trying to run this command:

`TriSeq -in chr_10.9750001-9800000_new.fasta -if fasta -of fasta -o chr_10.9750001-9800000_new_filter --missing-filter 0 35`

I obtain this message:
usage: TriSeq [-h] [-in INFILE [INFILE ...]]
              [-of {nexus,phylip,fasta,mcmctree,ima2,stockholm,gphocs,snapp} [{nexus,phylip,fasta,mcmctree,ima2,stockholm,gphocs,snapp} ...]]
              [-o OUTFILE] [-c] [-r REVERSE] [-z ZORRO]
              [-s [SELECT [SELECT ...]]] [--collapse] [--code-gaps]
              [--consensus {First sequence,IUPAC,Soft mask,Remove}]
              [--consensus-single-file] [--missing-filter M_FILTER M_FILTER]
              [--min-taxa MIN_TAXA]
              [--contain-taxa [CONTAIN_FILTER [CONTAIN_FILTER ...]]]
              [--exclude-taxa EXCLUDE_FILTER]
              [--codon-filter [{1,2,3} [{1,2,3} ...]]]
              [--variable-filter VAR_FILTER VAR_FILTER]
              [--informative-filter INF_FILTER INF_FILTER] [-p PARTITION_FILE]
              [--suffix OUTPUT_SUFFIX]
              [--model {DAYHOFF,DCMUT,JTT,MTREV,WAG,RTREV,CPREV,VT,BLOSUM62,MTMAM,LG}]
              [--interleave]
              [--ima2-params IMA2_PARAMS IMA2_PARAMS IMA2_PARAMS IMA2_PARAMS]
              [-rm [REMOVE [REMOVE ...]]] [-grep [GREP [GREP ...]]]
              [--get-taxa] [-quiet]
TriSeq: error: unrecognized arguments: -if fasta

The manual includes -if Input_format as one of the options. Everything works correctly, but just wanted to point that out.

This command worked:
`TriSeq -in chr_10.9750001-9800000_new.fasta -of fasta -o chr_10.9750001-9800000_new_filter --missing-filter 0 35`

**Comment by ODiogoSilva** [comment]
Hi Mafalda,

Thank you for pointing this out. The `-if` option was removed from TriSeq but the manual was not updated accordingly. Since you may provide multiple input files in different formats, we decided to remove an explicit input format option, which could inadvertently generate problems. TriSeq should be able to automatically detect the format of each individual input file, correct?

I'll leave this issue open until the manual is updated. 

Cheers,
Diogo

**Comment by MafaldaSFerreira** [comment]
Hi,

Yes, TriSeq did detect the input format correctly! 

Obrigada,
Mafalda

**Comment by MafaldaSFerreira** [comment]
I actually have a question regarding now the output of this (I don't think it's worth opening an issue for it, it's really just a question).

The output of the second command is the fasta file with lower-case dna sequences. Is this the normal behavior? It's easy enough to convert to upper case, but I was just wondering if this is the intended behavior given some programs interpret lower-case dna sequences as soft-masked. 

Thank you!
Mafalda

**Comment by ODiogoSilva** [comment]
Sequence data is always converted to lower case when loaded intro TriSeq/TriFusion to ensure consistency throughout its operations. This is a behaviour similar to other phylogenetic software, like mafft.  It also removes the overhead of having to convert the case of the characters when performing an operation that is case-sensitive. 

That said, it's fairly easy to include an option in TriSeq/TriFusion to convert sequence data into upper case when writing the output files. I would appreciate if you could open a new issue with a feature request. We are currently testing the release candidate for version 1.0.1 a this could be included in the next version. Also, feel free to poke around the code.

**Comment by MafaldaSFerreira** [comment]
Thank you! Will do.
